apiVersion: apps/v1
kind: Deployment
metadata:
  name: karma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karma
  template:
    metadata:
      labels:
        app: karma
    spec:
      containers:
        - name: karma
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.port }}
          env:
            - name: ALERTMANAGER_URI
              value: "http://{{ .Values.alertmanager.service }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.alertmanager.port }}"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
