{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app.kubernetes.io/name: shop
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
spec:
  instances: {{ .Values.postgres.instances }}
  imageName: {{ .Values.postgres.imageName }}
  inheritedMetadata:
    labels:
      {{- toYaml .Values.commonLabels | nindent 6 }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.username }}
  storage:
    size: {{ .Values.postgres.storage.size }}
  resources:
    {{- toYaml .Values.postgres.resources | nindent 4 }}
  enableSuperuserAccess: false
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: {{ .Values.postgres.podMonitor }}
{{- end }}
